#!/usr/bin/env node
// schema/ → src/generated/: the only way anything Python-owned reaches the TS side.
//
// The Python package is the SSOT (falaw/plan.py, falaw/results.py, falaw/base.py, the catalogue
// in falaw/data/models.json). `python -m falaw export-schema` writes the committed `schema/`
// directory at the repo root; this script turns it into TypeScript:
//
//   schema/call-plan.schema.json     →  src/generated/call-plan.ts     (Zod + CallPlan type)
//   schema/result.schema.json        →  src/generated/result.ts        (Zod + Result/Asset types)
//   schema/model-record.schema.json  →  src/generated/model-record.ts  (Zod + ModelRecord type)
//   schema/models.json               →  src/generated/models.ts        (the catalogue as data +
//                                                                       its table-version digest)
//   schema/constants.json            →  src/generated/constants.ts
//
// The catalogue's digest is computed from the committed file's BYTES here, the same way
// falaw.base.data_table_version does, so a CostBasis stamped in the browser names the same
// table version as one stamped in Python. The parity fixtures under schema/fixtures/ are
// not generated into code — the vitest suite reads them directly.

import $RefParser from '@apidevtools/json-schema-ref-parser';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TS_ROOT = resolve(__dirname, '..');
const REPO_ROOT = resolve(TS_ROOT, '..');
const SCHEMA_DIR = resolve(REPO_ROOT, 'schema');
const OUT_DIR = resolve(TS_ROOT, 'src/generated');
const TABLE_VERSION_CHARS = 12; // falaw.base.TABLE_VERSION_CHARS

const HEADER = (source) =>
  `// GENERATED by ts/scripts/codegen.mjs from schema/${source} — do not edit.\n` +
  '// The Python package is the SSOT; run `python -m falaw export-schema` then `npm run codegen`.\n\n';

class CodegenError extends Error {}

function readRaw(name) {
  const path = resolve(SCHEMA_DIR, name);
  if (!existsSync(path)) {
    throw new CodegenError(`missing ${path}\nRun \`python -m falaw export-schema\` first.`);
  }
  return readFileSync(path);
}

const readJson = (name) => JSON.parse(readRaw(name).toString('utf8'));

async function zodModule(file, name, type, extra = '') {
  const schema = await $RefParser.dereference(readJson(file));
  const code = jsonSchemaToZod(schema, { name, module: 'esm', type });
  return HEADER(file) + code + '\n' + extra;
}

function modelsModule() {
  const bytes = readRaw('models.json');
  const digest = createHash('sha256').update(bytes).digest('hex').slice(0, TABLE_VERSION_CHARS);
  return (
    HEADER('models.json') +
    "import { z } from 'zod';\n" +
    "import { type ModelRecord, modelRecordSchema } from './model-record';\n\n" +
    '/** Digest of the committed catalogue bytes — what a CostBasis records as `table_version`. */\n' +
    `export const MODELS_TABLE_VERSION = ${JSON.stringify(digest)};\n\n` +
    '/** The fal model catalogue, in catalogue order (curated entries first). Parsed through the\n' +
    ' *  schema at import so every record carries its defaults, as the Python dataclass does. */\n' +
    `export const MODELS: readonly ModelRecord[] = z.array(modelRecordSchema).parse(${JSON.stringify(JSON.parse(bytes.toString('utf8')), null, 2)});\n`
  );
}

function constantsModule() {
  return (
    HEADER('constants.json') +
    `export const CONSTANTS = ${JSON.stringify(readJson('constants.json'), null, 2)} as const;\n`
  );
}

/** Every generated module keyed by path under src/generated/ — one code path for CLI and test. */
export async function buildModules() {
  return {
    'call-plan.ts': await zodModule(
      'call-plan.schema.json',
      'callPlanSchema',
      'CallPlan',
      '// The pre-parse twin: fields the schema defaults are OPTIONAL here.\nexport type CallPlanInput = z.input<typeof callPlanSchema>\n',
    ),
    'result.ts': await zodModule(
      'result.schema.json',
      'resultSchema',
      'Result',
      "export type Asset = Result['assets'][number]\n",
    ),
    'model-record.ts': await zodModule(
      'model-record.schema.json',
      'modelRecordSchema',
      'ModelRecord',
      '// The pre-parse twin: a catalogue row as committed, defaults optional.\nexport type ModelRecordInput = z.input<typeof modelRecordSchema>\n',
    ),
    'models.ts': modelsModule(),
    'constants.ts': constantsModule(),
  };
}

export function committedModule(name) {
  const path = resolve(OUT_DIR, name);
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}

export { OUT_DIR, SCHEMA_DIR };

if (resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  try {
    const modules = await buildModules();
    if (check) {
      const stale = Object.keys(modules).filter((n) => committedModule(n) !== modules[n]);
      if (stale.length) {
        console.error(`codegen: STALE ${stale.join(', ')} — run \`npm run codegen\` and commit.`);
        process.exit(1);
      }
      console.log('codegen: generated modules are up to date ✓');
    } else {
      mkdirSync(OUT_DIR, { recursive: true });
      for (const [name, text] of Object.entries(modules)) {
        writeFileSync(resolve(OUT_DIR, name), text);
        console.log(`codegen: wrote src/generated/${name}`);
      }
    }
  } catch (err) {
    console.error(`codegen: ${err.message}`);
    process.exit(1);
  }
}
